INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (1, 'ボランティア', 'ほ' ,8,'無償の奉仕をする人のこと。地元のゴミ拾いからイベントの手伝いなどいろいろなボランティアがある。有償のボランティアも存在する。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (2, '生徒会長', 'せ', 4 , '中学・高校における政治を行う生徒会の代表者。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (3, 'ノマド', 'の', 6, '「遊牧民」という意味。喫茶店で仕事をすることスタイルのこと。時間軸や国境を超えて場所を転々としながら仕事をする生き方という説もある。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (4, '人生','し',7, '人生 人の一生のこと。長いようで実際は短い。コンテニューはない。気がついたら残り少ない。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (5, '世界','せ',8,'70億人の人間が住んでいる場所の総称。7割は海。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (6, '旅','た',4, '住んでいる場所から離れた場所へ行き、新しい体験をすること。LCCの普及もあり海外への旅がしやすい時代となった。日本から出る時に掛かる費用が大きい。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (7, '起業','き',9 ,'新しい事業をもとに会社を興すこと。言うは易し、行うは難し' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (8, 'マッキンゼー','ま',7,'総称は「マッキンゼー・アンド・カンパニー」。1流のコンサルタント会社。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (9, 'MIT', 'm', 4 ,'マサチューセッツ工科大学のこと。アメリカ マシューセッツ州ケンブリッジ市に本部がある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (10, '副業','ふ',3 , '本業とは別にする仕事。副業が成功し本業とするケースもある。せどりやウェブサイトの広告収入などがある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (11, 'メルマガ','め',5, 'まぐまぐを筆頭に近年復活をとげたシステム。堀江貴文が開拓したと言われる。ブログでは知ることができない話を知ることができる一方、肯定者が集まりやすいため否定の意見がでづらいなどと賛否両論がある。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (12, '自由','し',2, '柵を解き放ち、何にも縛られないこと。脱サラリーマンを目指してる人の価値観に多い。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (13, '笑顔','え',4, '嬉しい時に表れる表情。幸せに生きるために必要なもの。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (14, '読書','と',5, '本を読む行為。教養や知識が高められ、思考能力を鍛えることにも適している。また、娯楽として小説を読むこと。' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (15, 'コンサルティング','こ',6,'企業や機関に対して専門知識を活用し、問題点を見つけ改善策を提案すること' );
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (16, '経済学部','け',2,'');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (17, '商学部','し',2,'簿記などの会計法を中心に学ぶ学部。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (18, '感謝','か',3,'ありがたいと思う気持ちを表すこと。感謝すること');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (19, '学生団体','が',2,'何かしら社会に影響を与える活動を行う団体。就職活動のアピールに使われる。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (20, 'サークル','さ',1,'大学生活を大きく左右する選択の一つ。活動そのものを目的に活動する団体。運動部であっても実際は飲み会メインなサークルもある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (21, '自己啓発','し',7,'充実した人生・人間関係、社会的成功を求めて取り組む行動のこと。人に啓蒙したくなりがち。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (22, '座右の銘','さ',5,'自分を表す格言のこと。管理人の座右の銘は「始まりは半分」');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (23, '留学','り',9,'他国で学業を学ぶこと。近年では、フィリピンの英会話短期語学留学の人気が高い。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (24, '英語','え',7,'公用語として使われている言語で世界一。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (25, '英会話','え',7,'英語を使って会話を行なうこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (26, '夢','ゆ',2,'人生を通して成し遂げたいこと。もしくは、睡眠中にみる別世界。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (27, 'アジア','あ',4,'ユーラシア大陸の大部分を占める地域の名称。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (28, 'ジョブズ','し',5,'Apple創設者スティーブ・ジョブスのファミリーネーム。ギブンネームはスティーブン。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (29, 'apple','a',5,'MacintoshやiPhoneを開発・販売する会社。アメリカ カリフォルニア州クパティーノに本社がある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (30, 'ヒッチハイク','ひ',4,'目的地を書いた看板を持って、通りゆく車に目的地まで載せてもらう移動方法。コミュニケーション能力が求められる。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (31, 'ウェブ','う',1,'インターネットを通して文字や画像をやりとりできるもの。HTTP・URI・HTML・RESTといった技術から成り立つ。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (32, 'フォロー','ふ',1,'twitterで特定の人のツイートを自分のタイムラインに載せる行為。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (33, 'リムーブ','り',1,'twitterで特定の人のツイートを自分のタイムラインから外す行為');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (34, '代表','た',3,'グループで最も権力を持った人。グループの顔。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (35, 'ビジネス','ひ',2,'お金を稼ぐ経済行為のこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (36, 'Facebook','f',3,'月間アクティブユーザ11.1億人のソーシャルネットワークサービス。同僚や友達と交流を深めるのに役立つ。最近では連絡先の交換手段として電話番号はなくFacebookで繋がることが多い。誰とでも繋がれてしまうために、人間関係が複雑になってしまい、Facebook疲れする人も多い。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (37, '取締役','と',2,'株式会社で株主総会で選出された会社の運営を行なう経営者のこと。すべての株式会社に置かなければならない機関。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (38, '一期一会','い',4,'茶道の心得。この先もう2度と会えないかもしれないと気持ちで人と接すること。幕末に井伊直弼が広めた。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (39, 'ブログ','ふ', 2,'ウェブログのこと。自分の生活や考え方やノウハウをインターネット上に記録すること。livedoorブログ、はてなブログ、アメブロといったサービスがある。管理人ブログはWordpressを使用している。');        
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (40, '更新','こ',1,'新しく改めること。記録更新・ブログ更新・契約更新など');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (41, '運動','う',1, '体を動かすこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (42, 'おはよう','お',1, '朝の挨拶。交わしたお互いが気持ちのいいスタートを切れる言葉。芸能界や飲食業界では1日使われる。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (43, 'こんにちは','こ', 1, '昼の挨拶。交わしたお互いが幸せになる言葉。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (44, 'こんばんは','こ',1, '夜の挨拶。挨拶の中では1番使われていない気がする。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (45, '寝てない','ね',2, 'やることが多く睡眠を満足にとれてない時に発言しがち。寝ましょう。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (46, 'プログラミング','ふ',3, '意図した処理を行うようにコンピュータに指示を与えるプログラムを書くこと。近年はドットインストールをはじめとしたオンライン学習によって学習コストが下がっている。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (47, '簿記','ほ', 2,'資産・負債・純資産の増減を貸借対照表・損益計算書で管理し、一定期間内の収益と費用を記録すること。おもに複式簿記のことをさす。会社の決算に必要。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (48, '検定','け', 3,'試験を受けることにより基準の合否や等級を認定すること。就職や転職でみられるステータスの1つ。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (49, '資格','し', 4,'試験を受けて合格したらもらえるもの。資格を持たなければできないものとして、狩猟やダイビングがある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (50, '仕事','し',2 ,'生活を維持するために必要な経済活動。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (51, 'カンボジア','か',5,'インドシナ半島に位置するカンボジア王国。公用語はクメール語。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (52, '尊敬','そ',1 ,'特定の人の人格を敬い認めること。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (53, '覚悟','か',1, '起こりうる困難を予測して、受けとめる心構えをすること。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (54, 'オーガニック','お', 2, '化学肥料や農薬に頼らず、自然に作物を育てる農法。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (55, '玄米','げ',4, '精米する前の米。完全食に最も近いと言われる食物。ミネラルが不足するためゴマ塩必須。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (56, '稲盛和夫','い',2,'京セラ創業者でありJALの名誉会長。「人として正しい選択をする」「心を鎮める時間を作る」など格言が多い。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (57, '行動','こ',2,'実際に何かをすること。「行動なんだよ人生は」とは後藤利根雄の台詞である。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (58, '目標','も',3,'自分が達成すべき数値に表わすことのできる具体的な基準。目的と混同すると道を誤ることが多い');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (59, '中国','ち',4,'13億人の人口を持つアジアに位置する巨大国家。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (60, 'コミュニケーション','こ',1,'相手を理解し、交流すること。複数でプロジェクトを進める場合に必要。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (61, 'ロハス','ろ',1,'Lifestyles Of Health And Sustainabilityのこと。自然と共存して共に生きる考え方。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (62, 'プレゼン','ふ',1,'プレゼンテーションの略。企画やアイデアを人に伝える');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (63, 'インターン','い',2,'一定期間の間、学生が企業で研修を受けて働くこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (64, 'ザッカーバーグ','さ',5,'Facebook創業者 マーク・ザッカーバーグのファミリーネーム。自分で絞めた肉だけ食べないビリオネア。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (65, 'やりたいこと','や',3,'見つけるのが難しいもの。見つけたと思っても実際は違ったりすることがある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (66, '財産','さ',2,'手持ちの資産や友人など、かけがえのない大切なもののこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (67, 'linkedin','l',3,'ビジネスに特化したソーシャルネットワーク。ロンドンではFacebookより使われているらしい。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (68, 'クリエイティブ','く',1, '創造力があることを意味する。広告の場合だとバナーを指す。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (69, '想像','そ',1,'体験してないことをしたかのように頭の中で考えること。想像できないことは実現できないという説もある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (70, 'マネジメント','ま',4,'管理すること。飲み会の幹事からプロジェクトマネジメントまでさまざまな種類のマネジメントが存在する。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (71, '政治','せ',2,'集団における意志決定やルールを決めること。国の政治から、町の政治、会社の政治がある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (72, 'ハーバード','は',3,'大学の名前。米国最古の高等教育機関である。メールアドレスの@harvard.eduはアメリカ人にとって憧れのドメインらしい。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (73, 'リーダー','り',4,'集団を牽引する存在のこと。現在の日本であれば安倍晋三,SMAPであれば中居正広。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (74, '投資','と',2,'利益を目的として事業や株・国債などに資金を投入すること。自分にお金をかけることを自己投資と呼ぶこともある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (75, 'セミナー','せ',3,'専門の知識を持つ講師が技術や思想を伝授するためのイベント。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (76, '価値','か',2,'主に物に対する評価のことをさす。価値があるものは価格が高い。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (77, 'インド','い',7,'南アジアにあるインド共和国のこと。1度行ったら大好きになる人と2度と行かなくなる人で分かれる。何を食べてもカレー味がして、8割の人民は騙そうとしてくる(らしい)。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (78, 'マイノリティ','ま',4,'少数派であり立場が低い人達のこと。対義語はマジョリティ。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (79, '常識','し',3,'一般社会で当然と思われていること。国境を1つ越えるだけで全く違うものになる。囚われてしまうと自由に生きることが難しい。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (80, '議論','き',2,'1つのテーマについて複数人で話し合うこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (81, 'ブレスト','ふ',4 ,'ブレインストーミングのこと。お互いの意見を否定せず、アイデアを出し合う方式。１人で行なうことをセルフブレーンストーミングという。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (82, '読了','と',2,'本を読み終わったこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (83, 'イノベーション','い',3,'周りに影響を与える新しいアイデアや価値のこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (84, 'ニーチェ','に',2,'ドイツの哲学者、フリードリヒ・ニーチェのこと。チャームポイントは髭。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (85, '金持ち父さん','か',2,'ロバート・キヨサキ著「金持ち父さん貧乏父さん」の成功しているほうのお父さん。確か血は繋っていない。お金に働いてもらうことで安定した不労所得を得ている人。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (86, '貧乏父さん','ひ',2,'ロバート・キヨサキ著「金持ち父さん貧乏父さん」の失敗しているほうのお父さん。学歴が高く1流の会社に勤めているが、自由な時間が無く負債を背負っている人');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (87, '書評','し',5,'本を読んだ感想をブログなどに書き、評価すること');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (88, 'スタンフォード','す',2,'シリコンバレーにある世界屈指の名門大学。インターネット上で講義を無料で提供している。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (89, 'アンソニー・ロビンズ','あ',2,'世界No1コーチの異名を持つ。人生を変えさせる影響力がある。昔は風呂場で皿を洗うほど極貧だった。NLPという魔法を使う。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (90, '7つの習慣','な',4,'スティーブン・R. コヴィーによる自己啓発本。主体性を持ったり、目的意識を持つなどの習慣。愛読書としている著名人が多い。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (91, '人生を変える','し',2,'かなり難しい。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (92, '設計','せ',3,'制作までの過程を図に表すこと。人生設計,デザイン設計など。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (93, '夢をかなえるゾウ','ゆ',4,'水野敬也による100万部を突破した日本を代表する自己啓発書。自己啓発に必要な要素が全て揃っており、笑いありと');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (94, 'ちきりん','ち',3,'おちゃらけ社会派ブロガー。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (95, '速読','そ',4,'通常の数倍の速度で本を読み、かつ理解する読書術。専門学校も存在する。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (96, '速聴','そ',4,'通常の数倍の速度で音源を聞き、脳に刺激を与える方法。英語の聞きとり練習にも使われる。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (97, 'カーネギー','か',3,'デール・カーネギーやアンドリュー・カーネギーなど偉人');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (98, '人を動かす','ひ',6,'デール・カーネギーによる人間関係に関する自己啓発本の元祖。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (99, '朝活','あ',7,'通学前や出勤前にカフェなどで勉強したり読書会を開催すること');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (100, '異業種交流会','い',1,'さまざまな職種の人が集り名刺を交換しあう会。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (101, 'アイデア','あ',2,'新しい切り口や問題解決のための実現方法のこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (102, 'モレスキン','も',6,'高いノート。人生を変えるとまでいわれている。管理人は買ったけど使っていない。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (103, '仕事は楽しいかね','し',3,'デイル・ドーテンによる人気の高い自己啓発書。人生に悩む男性が空港で出逢った1人のメンターから教えを請い、人生が変わるという典型的な展開。人間関係を題材にした仕事はたのしいかね2も根強い人気がある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (104, '収益型住宅','し',6,'自宅の半分を賃貸として貸し出す住宅形態。税法上で優位になり、家を建てる時に覚えておきたい一つの手法。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (105, 'GTD','g',7,'デビットアレンが提唱するタスク管理術の1つ。Inboxとよばれるものに、頭の中にあるやらなければならないこと 悩んでいること いつかやりたいことを書き出し、定期的にいつやるかを決める手法。週ごとの見直しが面倒でやめてしまうことが多い。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (106, 'タスク','た',3,'やらなければいけないことの一覧。ToDoとの違いは人によって違う。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (107, 'ToDo','t',6,'やらなければいけないことの一覧。ToDoとの違いは人によって違う。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (108, 'スタバ','す',3,'世界チェーンのコーヒーカフェ。家でも職場でもない安心できる場所サードプレイスを目指しており、ノマドが集まるカフェの1つ。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (109, '挽きたて','ひ',4,'コーヒー豆を挽いたばかりの状態。ミルとよばれる機械を使う');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (110, '清貧','せ',1,'お金のあるなしに関わらず、私欲を捨て質素な生活を営むこと。もしくはかつて中野にあったセルフキッチンスタイルの居酒屋。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (111, 'テレビを持ってない','て',6,'最近の若者に多い。使える時間が増える、NHKの集金に堂々と持っていないと言えるなどメリットも多いが、周りの話題についてずに孤立する恐れもある。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (112, 'マーフィーの法則','ま',4,'共感できるありがちな法則。飲み会の日に限ってトラブルが発生するなど');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (113, '経済的自由','け',4,'金持ち父さん・貧乏父さんに影響を受けた人がよく口にする。一切金銭に困らない状態。実現できてる人は少ない。個人的に命の心配をする機会が多くなりそうで必ずしもよい状況とは言えないかも。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (114, 'TED','t',6,'至極のスピーチを閲覧できるウェブサービス。英語学習にもよく使われる。管理人のおすすめはMark Bezosの「A life lesson from a volunteer firefighter」とGraham Hillの「Less stuff, more happiness」。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (115, '物を持たない生活','も',8,'物を捨て身軽になり最低限の物で生活をすること。不便のように思われるが気持ちもすっきりする。また引っ越すのが楽。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (116, 'macbook','m',5,'appleのモバイルノートブックパソコン。スターバックスでノマド作業している人が所有していることが多い。オシャレかつプログラミングをする人にとっては開発環境を整えるのが容易で重宝される。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (117, 'MBT','m',6,'マサイベアフットテクノロジーのこと。履くことでマサイ族と歩行姿勢をとることができ、歩くだけ運動した効果が得られる画期的なシューズ。高城剛や松嶋奈々子が愛用している。懸念点として価格が高くデザインがよくない。管理人は初めて履いた日に歩きすぎて発熱した。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (118, 'ソー活','そ',3,'TwitterやFacebookなどソーシャルネットワークを活用した就職活動のこと。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (119, 'ロジカルシンキング','ろ',3,'論理的な考える思考方法。プライベートで使うと嫌われてしまうこともある。使い分け大事。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (120, 'MECE','m',3,'物事をモレがなくダブりのない状態にすること。ロジカルシンキングに使われる。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (121, 'Twitter','t',6,'ツイートと呼ばれる140文字以内の文章を投稿してコミュニケーションをとるウェブサービス。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (122, 'デュアルライフ','て',5,'2箇所以上に拠点を置いて生活する人。拠点が国境を越える場合もある。人気の地域としてハワイ、イビサ、サンセバスチャン、バンコク、セブ、台北などがある。人気というか管理人が住みたいところです。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (123, 'アーユルヴェーダ','あ',3,'インド大陸の伝統的医学。個人の体質を知り、ヴァータと呼ばれる属性によって食べ物や治療法を変えるもの。近年ではスリランカのアーユルヴェーダに根強い人気がある。慢性的に悩まされていた病を克服するという例も多数ある。最低でも2週間の滞在が必要と言われる。日本国内のアーユルヴェーダを謳う製品は名を使った擬い物である。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (124, '断捨離','た',3,'ヨガの行法。不要な物を捨て、物への執着を無くし心の調和を導く生き方や考え方。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (125, 'ベーシックインカム','へ',2,'毎月すべての人に一定の所得を与えるという最低保証程度の1つ。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (126, 'ゴールドカラー','こ',7,'人生における移動距離が長い人。仕事範囲がグローバルな人を言う。主体的に仕事を行ない、雇われていながらも指示されずに自分で仕事を作り達成する人。');
INSERT INTO keywords ('id',  'name', 'initial_letter' , 'value', 'description') VALUES (127, 'スターバックス','す',3,'世界チェーンのコーヒーカフェ。家でも職場でもない安心できる場所サードプレイスを目指しており、ノマドが集まるカフェの1つ。');


